### ISSUE TITLE
Get icons from materialdesignicons.com instead of hardcoding list

### ISSUE THREAD

**Issue by chteuchteu** [chteuchteu/MaterialDesignIcons-Picker#1]
For now, icons list is hardcoded in [/data/browser-actions/js/icons.js](/data/browser-action/js/icons.js).
We should probably download this list from materialdesignicons.com & cache it in `localStorage` so we don't have to publish new versions of this extension when new icons comes out.

**Comment by Templarian** [comment]
Oh, I may be able to help you with this... there is a meta JSON file that I can generate and upload in the CDN folder that includes all the alias information and version that the icon exists in.

It's a little DB intensive so it would need to be cached, but I think it would be worth my time for you and others that want to build tools like this.

**Comment by chteuchteu** [comment]
Hi!
First, thank you a lot for MaterialDesignIcons (shoutout to the others contributors too): I'm using it in some of my projects and was glad to find quality icons (I've never been a big fan of FontAwesome and never found a good icons font until MDI)

That would be _great_! `_variables.scss` was good enough for [MaterialDesignIcons-SCSS-Variables](https://github.com/chteuchteu/MaterialDesignIcons-SCSS-Variables) and [MaterialDesignIcons-CSharp-Consts](https://github.com/chteuchteu/MaterialDesignIcons-CSharp-Consts/), but alias information, author & version information would be a great addition to this project.

Is there anything I can do to help?

**Comment by Templarian** [comment]
Nah, not really anything to do on your side. I'll try and work on this tomorrow (working on a few open source project backlog things tomorrow).

http://cdn.materialdesignicons.com/1.5.54/meta.json Was a test of this system, but I never generated it for 1.6.50 due to some issues. The same fix for [#1379](https://github.com/Templarian/MaterialDesign/issues/1379) solves my meta json issue, and that's currently pretty high priority for tomorrow to fix.

**Comment by Templarian** [comment]
Actually... is there anyway you can use the blue/[vector-square](https://materialdesignicons.com/icon/vector-square) icon. I would like to feature this on the site (like in the footer/getting started page), would be nice if matched the site's branding. Right now it looks more like an emoji extension.

![image](https://cloud.githubusercontent.com/assets/338885/17080050/bec17b98-50e7-11e6-8a35-03b4e0e953ae.png)

(quick screenshot from the top left of the site, probably can make it more pixel perfect, by modifying it)

**Comment by chteuchteu** [comment]
Thanks! I'll implement this soon, and wait until #1379 is fixed to release it.
Sure I can!

This is totally off-topic, but is MDI's website (its CSS specifically) in a public repo? I'd like to make some PRs if it's OK

**Comment by chteuchteu** [comment]
I'm using your JSON file in [json_upstream_source](https://github.com/chteuchteu/MaterialDesignIcons-Picker/tree/json_upstream_source), it works like a charm!

I'll wait until your issue is fixed to merge it. Would it be possible to add author information in addition to version?

Thanks!

**Comment by chteuchteu** [comment]
@Templarian Any news on the meta JSON file?

**Comment by Templarian** [comment]
Working on it. Busy with back to back summer events Should have some time tonight to wrap up the changes and upload the meta.json for `v1.6.50`. Trying to get the tags in the export also (but our tagging is way behind at the moment, so it won't be that useful yet).

**Comment by chteuchteu** [comment]
Great, thanks! Will there be a *http://cdn.materialdesignicons.com/latest/meta.json*? That would be great!

**Comment by Templarian** [comment]
I've thought about it, but we do renames once in a while which are breaking changes and I really don't want people to assume `/latest` will match all their previous icons. Like in the next release `outbox` will be renamed to `inbox-arrow-up`.

To reach a middle ground we could do the same thing, but name it `/develop` to make it more apparent this could contain breaking changes at any time (that would match the site closer).

**Comment by chteuchteu** [comment]
Good point indeed.

What about using semantic versioning then? The con is that major version number could increment quite quickly if a lot of releases includes breaking changes though. We could then use `3.x.x` or `3-latest` for both assets in CDN & JSON meta files.

`/develop` would be a good alternative

I'm reopening this issue, I'll close it when the JSON meta file will be available!

**Comment by Templarian** [comment]
We do "sort of" use semantic versioning. With the assumption that there will always be more icons we just increment the version with the icon count. I don't think I'm going to ever do real versioning for this project since I never plan to support legacy versions with updates. If someone wants a new icon they will have to use a version that contains said icon.

Okay, I'll link `/develop` folder in our cdn (will let you know when this is done).

**Comment by chteuchteu** [comment]
Awesome, thanks!

**Comment by Templarian** [comment]
Just an update, still working on this. Almost there, should have it wrapped up this weekend (with the author names included).

**Comment by chteuchteu** [comment]
Great! I released [v1.3.0](https://github.com/chteuchteu/MaterialDesignIcons-Picker/releases/tag/v1.3.0) 2 days ago, still have to update screenshots.

**Comment by chteuchteu** [comment]
One more thing: how can I know the last published version of the library? For now I can parse [_variables.scss](https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/scss/_variables.scss)'s `$mdi-version` variable. Is this reliable?

**Comment by Templarian** [comment]
https://cdn.materialdesignicons.com/1.6.50/meta.json

I'm going to be doing a release for 1.6.74 probably Friday that contains a good amount of updates. I'll include authors in that meta.json file.

**Comment by chteuchteu** [comment]
Great, thanks! You talked about a "version" attribute on each icon. Will it be available?

**Comment by Templarian** [comment]
Yes... I can add that also, but it only goes back 2 versions. Since versioning is still very new.

1.5.54, 1.6.50, and new 1.6.74.

**Comment by chteuchteu** [comment]
Great! Not a problem. Will version be null if it is unknown, or will it take the lowest value (1.5.54)?

**Comment by Templarian** [comment]
I just put everything at 1554 into v1.5.54 so yea. That was the first version where I fixed the codepoints so they are consistent over versions.

**Comment by chteuchteu** [comment]
Alright!

Everything is ready on my side:
- [MDI-Upstream-Parser](https://github.com/chteuchteu/MaterialDesignIcons-Upstream-Parser/blob/master/mdi_upstream.py#L38) gets meta from the latest available JSON file. `author` and `version` values fallbacks to null for now
- [`update-icons-list.py`](https://github.com/chteuchteu/MaterialDesignIcons-Picker/blob/master/update-icons-list.py#L54) script now uses MDI-Upstream-Parser, [icons(.min).js](https://raw.githubusercontent.com/chteuchteu/MaterialDesignIcons-Picker/master/data/icons.json) gets properly filled
- Author & version information will be hidden when null ([see here](https://github.com/chteuchteu/MaterialDesignIcons-Picker/blob/master/data/browser-action/js/script.js#L226))

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.7.12/meta.json here is the latest JSON file.

Fixing some minor issues in the build at the moment and will have it uploaded shortly (right now `meta.json` is the only file in that release folder).

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.7.12/ Is up for preview attached is the download, I'll be doing a npm/bower release tomorrow. Just know `mdi-blank` is not a real icon, so it won't show up in the meta.json file, if you want it just add it manually and assume the codepoint is `f68c`.

[MaterialDesignIcons.zip](https://github.com/chteuchteu/MaterialDesignIcons-Picker/files/424207/MaterialDesignIcons.zip)

**Comment by chteuchteu** [comment]
Great, thank you! Since my script is relying on [_variables.scss](https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/scss/_variables.scss)'s `$mdi-version` variable, I'll have to wait for it to be updated.

I'll release a new version of the picker once everything will be ready. Thanks!

**Comment by Templarian** [comment]
Updated. Good luck with the extension! I'll be building out a resources page that makes it quicker for people to find and download shortly.
