### ISSUE TITLE
Latest version automatically colors the icons

### ISSUE THREAD

**Issue by goyney** [chteuchteu/MaterialDesignIcons-Picker#15]
With the 2.1.99 update, all the icons are automatically colored. Toggling the colors off is not retained and the next time the panel is opened, colors are turned back on.

Can you please return the default setting to not be colored? Perhaps you can build in logic to retain which state you were in for subsequent openings of the panel, but by default, the colors are more distracting than anything.

**Comment by chteuchteu** [comment]
Thank you the bug report! I just spotted the issue - the color toggle state is actually persisted, but its value isn't correctly re-read on startup...

I'll fix it and publish a new update really soon, sorry about that!

**Comment by chteuchteu** [comment]
I just published the release, it should be available in a minute!
