### ISSUE TITLE
Add the ability to download the SVG directly from the panel

### ISSUE THREAD

**Issue by goyney** [chteuchteu/MaterialDesignIcons-Picker#16]
It would be lovely if you could click on an icon and have a dropdown that allows you to download the source SVG.

It would be a welcome shortcut instead of having to follow the link to the MDI site, waiting for it load, pulling the dropdown, and clicking the link to get the source. I use the SVG sources in UX prototypes a lot and this would save a lot of time.

**Comment by chteuchteu** [comment]
When you pick an icon, a "copy SVG" button appears, allowing you to copy the SVG path for the selected icon.

For instance, here's the content of the clipboard when using it with the `mdi-account-circle` icon:

```svg
<svg width="24" height="24" viewBox="0 0 24 24"><path d="M12,19.2C9.5,19.2 7.29,17.92 6,16C6.03,14 10,12.9 12,12.9C14,12.9 17.97,14 18,16C16.71,17.92 14.5,19.2 12,19.2M12,5C13.66,5 15,6.34 15,8C15,9.66 13.66,11 12,11C10.34,11 9,9.66 9,8C9,6.34 10.34,5 12,5M12,2C6.48,2 2,6.48 2,12C2,17.52 6.48,22 12,22C17.52,22 22,17.52 22,12C22,6.47 17.5,2 12,2Z" /></svg>
```

Does it satisfy your use-case?

Here's the icon:
![screenshot from 2018-03-08 19-11-17](https://user-images.githubusercontent.com/1551971/37168252-8d415dea-2304-11e8-8123-e1896beb3052.png)

**Comment by goyney** [comment]
It doesn't, unfortunately. I work in Adobe XD quite a bit (not sure if a copy/paste of SVG code works in something like Sketch). I have to download the SVG file and the drag it into the artboard to use it.

Even the raw copy/paste isn't typically useful for us specifically, because we're in React and use the mdi-react package to insert the SVGs in code, though I'm sure others probably use it.

**Comment by chteuchteu** [comment]
Alright! I'm not quite sure if file downloads are allowed inside a browser action though, I'll have to check.

Thank you for the feature idea!

**Comment by MrGrigri** [comment]
https://stackoverflow.com/questions/4845215/making-a-chrome-extension-download-a-file
