### ISSUE TITLE
Display Author / Codepoint on Tooltip

### ISSUE THREAD

**Issue by Templarian** [chteuchteu/MaterialDesignIcons-Picker#17]
This is a very niche probably low priority issue, but it would be helpful to have the author of the icon listed in a more advanced hover state.

- Name
- [ ] Author - Under name in the tooltip
- [ ] Codepoint - or a toggle to enable this in small text under the icon? The new site is getting this feature, we call it cheatsheet mode.

**Comment by chteuchteu** [comment]
We currently don't have much control over the tooltip format for now (I'm using the `title` attribute)
We'd have to introduce a tooltip library (or handle it ourselves). Note that all these information are available in the expanded toolbar that's shown on icon click:

![screenshot from 2018-03-24 21-07-53](https://user-images.githubusercontent.com/1551971/37868490-7664f190-2fa7-11e8-8c1d-fa0340875432.png)

What would be the use case for having these information available in a tooltip? Wouldn't it be redundant?

**Comment by Templarian** [comment]
That's okay then, yea having it when clicked is probably fine. Funny enough, I didn't click the icon since I generally am checking if the icon is there and the name. 🙃

**Comment by chteuchteu** [comment]
Since I created the extension, I always thought that it was pretty obvious that clicking on an icon would display its information :-) Should we make it more obvious? If so, how?

**Comment by Templarian** [comment]
It's fine, I'm a rare use case in this scenario. lol
