### ISSUE TITLE
Toggle between all, filled, and outline icons

### ISSUE THREAD

**Issue by JamesCoyle** [chteuchteu/MaterialDesignIcons-Picker#24]
Now that we are making a push to include outline variants for all icons it would be useful to have a way to filter the icons to show just the filled or outline variants. I'd implement this so that any icon that has an `*-outline` modifier only shows the filled/outline variant of that icon based on what the user has selected and every other icon just shows the normal filled state for both until we can add its outline variant.

**Comment by chteuchteu** [comment]
Nice one, I'm adding this to my todo list!

**Comment by chteuchteu** [comment]
As discussed with Austin, styles will soon be added to the `meta.json` file: we'll be able to easily handle all these variants at once!

**Comment by chteuchteu** [comment]
This has been implemented in [2.0.0](https://github.com/chteuchteu/MaterialDesignIcons-Picker/releases/tag/v2.0.0)
