### ISSUE TITLE
Enhancement: Auto-preview generation

### ISSUE THREAD

**Issue by goyney** [chteuchteu/MaterialDesignIcons-Picker#25]
There's many times I find myself wanting to grab the current version of an icon when answering issues for MDI. For me to do that currently, I have to find the icon in the add-on, open it up on the website, click "View SVG", copy paste the path data, [go to the preview generator](http://dev.materialdesignicons.com/contribute/github), paste it in, type in the name, flip the WIP switch, copy the image, go back to the issue, and finally paste it. Whew!

It would be a very welcome feature if there was another button at the bottom of the UI that, when an icon was selected, could be clicked that would generate the image and then:

- Copy it to my clipboard
  - Don't know if clipboard manipulation is possible via extensions, so this may not be feasible
- Pop open another window so I can right-click copy it

The auto-generated image I'm speaking about looks like this:
![image](https://user-images.githubusercontent.com/1015040/48817198-4a35c700-ed13-11e8-9acd-e8a96fc34466.png)

The code that generates this image can be found here: https://github.com/goyney/MaterialDesign-Site/blob/master/src/app/githubPage/githubPage.component.ts

I'm sure @Templarian wouldn't mind if you borrowed it. :)

**Comment by Templarian** [comment]
`[![icon-name](https://materialdesignicons.com/icon/icon-name)](https://materialdesignicons.com/icon/icon-name)` Actually will place an image. We scan the headers for an image request and return an image preview. 😃

**Comment by goyney** [comment]
That actually could make this insanely easy if extensions can work with the clipboard. Copy that string to my clipboard so I can just paste it in!

**Comment by chteuchteu** [comment]
@Templarian Awesome! Is there any endpoint documentation anywhere? Seems that GitHub loads this image on the server-side of `https://github.com/preview`

@goyney I think that's doable, I'll have to do some experiments first :-)

**Comment by PeterShaggyNoble** [comment]
[See also](https://github.com/PeterShaggyNoble/MDI-Sandbox/blob/master/README.md#preview-generator) 😉

**Comment by chteuchteu** [comment]
Nice!

**Comment by chteuchteu** [comment]
Hey there!
I finally can find some time to tackle this one, sorry about the _tiny_ delay.
Unfortunately, extensions aren't allowed to trigger external XHR (the extension would be rejected, at least on Firefox), so we can't stream `http://mdi.houseofdesign.ie/tools/preview/?icon=vector-square&action=link`'s response to the clipboard. The alternative would be to generate it in the extension.

@Templarian 's alternate proposal would be really easy to achieve (putting `[![icon-name](https://materialdesignicons.com/icon/icon-name)](https://materialdesignicons.com/icon/icon-name)` in the clipboard): would that suit your need?

**Comment by goyney** [comment]
Yeah that would be fine with me, it may not be super useful to other people using the addon because it would be GitHub specific there, but it would still be a big time saver for us maintainers if you decided to add it.

**Comment by chteuchteu** [comment]
Done! Since most users would not need this options, I added a "dev tools" toggle in the main dropdown:

![image](https://user-images.githubusercontent.com/1551971/133214751-86004a60-1a05-42c4-aae7-b148928ce73d.png)

When enabled, it adds the "Copy preview image" option in the icon dropdown:

![image](https://user-images.githubusercontent.com/1551971/133214835-1d26f9ef-9364-4f90-b9be-2f950fa60c48.png)

I also added subtitles to each dropdown item to make it even more explicit.

What do you think?
This will be released on the next update, when 6.2.95 is up!

[![vector-square](https://materialdesignicons.com/icon/vector-square)](https://materialdesignicons.com/icon/vector-square)
