### ISSUE TITLE
Copy icons when clicking on the icon preview to use on design applications

### ISSUE THREAD

**Issue by geiras** [chteuchteu/MaterialDesignIcons-Picker#46]
It takes a lot of steps to use Material Design Icons Font on design applications such as Figma.
The workflow of using the icon is:

1. Open the extension
2. Search for the icon
3. Click on the selected icon
4. Copy webfont icon name
5. Open Material Design CheatSheet (https://cdn.materialdesignicons.com/4.5.95/)
6. Open Find in Page
7. Paste webfont icon name
8. Click on the icon to copy to clipboard.

It's possible to reduce all the steps to half by allowing to copy the icon font to the clipboard when clicking on the selected icon (currently, it just changes colors).
![image](https://user-images.githubusercontent.com/22840903/68295582-9b58db00-008a-11ea-95c5-eb8d1b83fd21.png)

1. Open the extension
2. Search for the icon
3. Click on the selected icon
4. Click on the icon to copy to clipboard.

**Comment by chteuchteu** [comment]
+1, that'd be a great addition! The current behavior (changing primary color) isn't quite discoverable, and could easily be moved to the main overflow menu (on the top right corner of the extension)

Wouldn't it be better to add a "Copy icon" option in the icon dropdown, next to "Copy SVG"? It would a bit more explicit IMHO

Do you want to open a PR for this feature?

**Comment by geiras** [comment]
The current behavior of changing color is not discoverable but also not that useful.
But, we can keep the same behavior but also copy the icon to the clipboard. That would be the power user way of copying the icon. 

It should also be added to the overflow menu for easier discoverability, like you mentioned.

**Comment by chteuchteu** [comment]
@geiras What would be the expected clipboard content?

**Comment by chteuchteu** [comment]
@geiras Your "Open Material Design CheatSheet" link doesn't work anymore, I guess you meant https://pictogrammers.github.io/@mdi/font/6.2.95/

> What would be the expected clipboard content?
Did you meant `mdi-audio-input-stereo-minijack` for instance?

The "Copy name" action nearly achieves what you're expecting (it copies `audio-input-stereo-minijack` into your clipboard). 
Are you expecting the missing `mdi-` prefix, and/or being able to remove one click from your workflow?

We could let the user chose what do to (copy name / copy svg / copy svg path) when he clicks on the selected icon.
What do you think?

**Comment by chteuchteu** [comment]
Deployed on the last updated!

**Comment by geiras** [comment]
> @geiras What would be the expected clipboard content?

Hey there. Just saw this now, the notification was lost somewhere on my inbox. 

The expected clipboard content would be the same as if you did the exact same steps as I described on the original post.
I would expect it to copy the icon in a way that I could paste it on Figma or other design application. So, it’s the actual icon, not the name.

I agree that the dropdown could allow users to pick what does the action of clicking on the icon does. Like set it as a default.
Let me know if you have more questions. I can record a screen capture to make it easier to understand.

Will give it a try to the updated extension! Thanks for getting back to me.

**Comment by chteuchteu** [comment]
Could you check the latest extension version please? I implemented both. Let me know if it suits your workflow!

![Screenshot from 2021-09-22 10-28-18](https://user-images.githubusercontent.com/1551971/134309636-2fe233b2-21cf-45dc-a2dc-904d45da74c4.png)
![Screenshot from 2021-09-22 10-28-25](https://user-images.githubusercontent.com/1551971/134309640-98286b0c-40a2-4d00-b5fc-7b79dce06954.png)
